### ISSUE TITLE
JSON Format differs between Partie 2 and Partie 3 of Project

### ISSUE THREAD

**Issue by Schoumi** [johnsamuelwrites/AlgoC#6]
The json format differs. In [Partie 2](https://github.com/johnsamuelwrites/AlgoC/blob/master/Projet/partie2.md?plain=1#L78) you have colors only in "valeur" field when in [Partie 3](https://github.com/johnsamuelwrites/AlgoC/blob/master/Projet/partie3.md?plain=1#L37) you have the number of values at the begining of "valeur" field.

**Comment by johnsamuelwrites** [comment]
@Schoumi Thanks for pointing out this error. The example in the beginning now reflects the detailed example in lines [147](https://github.com/johnsamuelwrites/AlgoC/blob/master/Projet/partie3.md?plain=1#L147) and [169](https://github.com/johnsamuelwrites/AlgoC/blob/master/Projet/partie3.md?plain=1#L147).

In Partie 2, there was not any need to pass this count.
